baseurl = "https://www.arjen.eu"
languageCode = "en-us"
title = "Arjen's travels"
[params]
    subtitle = "The tales of what happens during my trips"
[indexes]
   country = "countries"
[permalinks]
    posts = "/:year/:month/:slug"
    pages = "/:slug/"
[[menu.social]]
    pre = "<i class='fa fa-twitter'></i>"
    url = "https://www.twitter.com/ArjenSchwarz"
    identifier = "twitter"
[[menu.social]]
    pre = "<i class='fa fa-instagram'></i>"
    url = "https://www.instagram.com/ArjenSchwarz"
    identifier = "instagram"
[[menu.social]]
    pre = "<i class='fa fa-envelope-o'></i>"
    url = "mailto:arjen@arjen.eu"
    identifier = "email"
[[menu.countries]]
    pre = ""
    Url = "/countries/australia"
    Name = "Australia"
[[menu.countries]]
    pre = ""
    Url = "/countries/cook-islands"
    Name = "Cook Islands"
[[menu.countries]]
    pre = ""
    Url = "/countries/fiji"
    Name = "Fiji"
[[menu.countries]]
    pre = ""
    Url = "/countries/germany"
    Name = "Germany"
[[menu.countries]]
    pre = ""
    Url = "/countries/new-zealand"
    Name = "New Zealand"
[[menu.countries]]
    pre = ""
    Url = "/countries/singapore"
    Name = "Singapore"
[[menu.countries]]
    pre = ""
    Url = "/countries/the-netherlands"
    Name = "The Netherlands"