on: push
name: Build and Deploy Hugo Site
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build
      uses: ArjenSchwarz/actions/hugo/build@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: --minify
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: GitHub Pages
      if: github.refs == "refs/heads/master"
      uses: ArjenSchwarz/actions/github/pages@master
      env:
        DOMAIN: www.arjen.eu
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ONLY_IN_BRANCH: master
